conformance_automated = "Pass"
errors_diff = """
"""
output = """
specialtypes_type.py:56: error: Argument 1 to "func4" has incompatible type "Type[TeamUser]"; expected "Type[BasicUser | ProUser]"
specialtypes_type.py:70: error: Argument 1 to "func5" has incompatible type "_SpecialForm"; expected "Type[Never]"
specialtypes_type.py:76: error: Invalid type comment or annotation
specialtypes_type.py:117: error: "Type[object]" has no attribute "unknown"
specialtypes_type.py:120: error: "Type[object]" has no attribute "unknown"
specialtypes_type.py:143: error: "_SpecialForm" has no attribute "unknown"
specialtypes_type.py:144: error: "_SpecialForm" has no attribute "unknown"
specialtypes_type.py:145: error: "_SpecialForm" has no attribute "unknown"
specialtypes_type.py:146: error: "_SpecialForm" has no attribute "unknown"
"""
